version: '3'
services:
  golang:
    image: golang:1.22
    container_name: golang
    environment:
      - GOOS=linux
      - GOARCH=amd64
    working_dir: /go/src/app
    volumes:
      - ./src:/go/src/app
    entrypoint: ["/bin/sh","-c"]
    command: 
      - |
        go mod tidy
        go build -o IBMStorageFS5K  *.go